[package]
name = "traced"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polyanya = { path = "../../", features = ["tracing"] }
glam = "0.24"
tracing-subscriber = "0.3"
tracing-tracy = "0.10"
tracing = "0.1"
geo-offset = { git = "https://github.com/mockersf/geo-offset", branch = "support-f32" }
