name: CodSpeed

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable

      - name: Install CodSpeed
        run: cargo install cargo-codspeed

      - name: Build the benchmark target(s)
        run: cargo codspeed build

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v5
        with:
          mode: instrumentation
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}

  benchmarks-detailed-layers:
    name: Run benchmarks (detailed-layers)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable

      - name: Install CodSpeed
        run: cargo install cargo-codspeed

      - name: Build the benchmark target(s)
        run: cargo codspeed build --features detailed-layers --bench path --bench no_path --bench layers

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v5
        with:
          mode: instrumentation
          run: cargo codspeed run --bench path --bench no_path --bench layers
          token: ${{ secrets.CODSPEED_TOKEN }}
